import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const mainActivity = readFileSync(resolve(process.cwd(), 'app/src/main/java/studio/broapp/lustigewitze/MainActivity.kt'), 'utf8');

test('feed screen keeps vertical scrolling free and only uses horizontal swipe voting', () => {
  assert.match(mainActivity, /FeedScreen\(/);
  assert.match(mainActivity, /FeedSwipeCard/);
  assert.doesNotMatch(mainActivity, /var dragY by remember/);
  assert.match(mainActivity, /detectHorizontalDragGestures/);
  assert.doesNotMatch(mainActivity, /dragY < -120f/);
  assert.match(mainActivity, /val voteValue = if \(dragX > 120f\) 1 else if \(dragX < -120f\) -1 else null/);
  assert.match(mainActivity, /Like registriert/);
  assert.match(mainActivity, /Dislike registriert/);
  assert.doesNotMatch(mainActivity, /Stern registriert/);
  assert.doesNotMatch(mainActivity, /Swipe, Buttons, Undo und Haptik-Aequivalent sind als MVP-State vorhanden\./);
  assert.match(mainActivity, /showTitle = false/);
  assert.match(mainActivity, /Modifier\.width\(72\.dp\)/);
  assert.match(mainActivity, /compactHorizontalPadding = 3\.dp/);
  assert.match(mainActivity, /compactVerticalPadding = 2\.dp/);
  assert.match(mainActivity, /compactHorizontalPadding: Dp = 6\.dp/);
  assert.match(mainActivity, /compactVerticalPadding: Dp = 11\.dp/);
  assert.match(mainActivity, /vertical = if \(showTitle\) 10\.dp else compactVerticalPadding/);
  assert.match(mainActivity, /horizontal = if \(showTitle\) 6\.dp else compactHorizontalPadding/);
  assert.match(mainActivity, /Modifier\.size\(if \(showTitle\) 24\.dp else 32\.dp\)/);
  assert.match(mainActivity, /else "Merken"/);
  assert.match(mainActivity, /Modifier[\s\S]*\.weight\(1f\)[\s\S]*\.padding\(start = 8\.dp\)/);
  assert.match(mainActivity, /private val MOBILE_HEADER_TOP_INSET = 8\.dp/);
  assert.match(mainActivity, /Box\(modifier = Modifier\.padding\(top = MOBILE_HEADER_TOP_INSET\)\) \{\s*ScreenHeader\(title = "Lustige Witze"/);
  assert.match(mainActivity, /Box\(modifier = Modifier\.padding\(top = MOBILE_HEADER_TOP_INSET\)\) \{\s*ScreenHeader\(title = "Zufallswitz"/);
  assert.match(mainActivity, /statusBarsPadding\(\)/);
  assert.match(mainActivity, /SwipeVoteBadge/);
  assert.match(mainActivity, /label = "TOP"/);
  assert.match(mainActivity, /Icons\.Filled\.ThumbUp/);
  assert.match(mainActivity, /label = "RUNTER"/);
  assert.match(mainActivity, /Icons\.Filled\.ThumbDown/);
  assert.match(mainActivity, /dragX > 24f/);
  assert.match(mainActivity, /dragX < -24f/);
});
