import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const mainActivity = readFileSync(resolve(process.cwd(), 'app/src/main/java/studio/broapp/lustigewitze/MainActivity.kt'), 'utf8');

test('feed screen keeps vertical scrolling free and only uses horizontal swipe voting', () => {
  assert.match(mainActivity, /FeedScreen\(/);
  assert.match(mainActivity, /FeedSwipeCard/);
  assert.doesNotMatch(mainActivity, /var dragY by remember/);
  assert.match(mainActivity, /detectHorizontalDragGestures/);
  assert.doesNotMatch(mainActivity, /dragY < -120f/);
  assert.match(mainActivity, /val voteValue = if \(dragX > 120f\) 1 else if \(dragX < -120f\) -1 else null/);
  assert.match(mainActivity, /Like registriert/);
  assert.match(mainActivity, /Dislike registriert/);
  assert.doesNotMatch(mainActivity, /Stern registriert/);
  assert.doesNotMatch(mainActivity, /Swipe, Buttons, Undo und Haptik-Aequivalent sind als MVP-State vorhanden\./);
  assert.match(mainActivity, /showTitle = false/);
  assert.match(mainActivity, /Modifier\.weight\(1f\)/);
  assert.doesNotMatch(mainActivity, /Modifier\.width\(72\.dp\)/);
  assert.match(mainActivity, /compactHorizontalPadding = 2\.dp/);
  assert.match(mainActivity, /compactVerticalPadding = 5\.dp/);
  assert.match(mainActivity, /compactHorizontalPadding: Dp = 6\.dp/);
  assert.match(mainActivity, /compactVerticalPadding: Dp = 11\.dp/);
  assert.match(mainActivity, /if \(showTitle\) \{[\s\S]*Row\([\s\S]*Icon\(icon, title[\s\S]*Text\(title, fontSize = 12\.sp/);
  assert.match(mainActivity, /Modifier\.size\(32\.dp\)/);
  assert.match(mainActivity, /else "Merken"/);
  assert.match(mainActivity, /Icons\.Filled\.Favorite,[\s\S]*Modifier\.weight\(1\.35f\),[\s\S]*showTitle = true/);
  assert.match(mainActivity, /private val MOBILE_HEADER_TOP_INSET = 6\.dp/);
  assert.match(mainActivity, /Box\(modifier = Modifier\.padding\(top = MOBILE_HEADER_TOP_INSET\)\) \{\s*FeedHeader\(/);
  assert.match(mainActivity, /Box\(modifier = Modifier\.padding\(top = MOBILE_HEADER_TOP_INSET\)\) \{\s*ScreenHeader\(title = "Zufallswitz"/);
  assert.match(mainActivity, /Scaffold\(\s*containerColor = MaterialTheme\.colorScheme\.background,\s*bottomBar =/, 'Scaffold should own safe system insets once the top banner is removed');
  assert.doesNotMatch(mainActivity, /statusBarsPadding\(\)/, 'The removed banner must not leave manual status-bar padding behind');
  assert.match(mainActivity, /SwipeVoteBadge/);
  assert.match(mainActivity, /label = "TOP"/);
  assert.match(mainActivity, /Icons\.Filled\.ThumbUp/);
  assert.match(mainActivity, /label = "RUNTER"/);
  assert.match(mainActivity, /Icons\.Filled\.ThumbDown/);
  assert.match(mainActivity, /dragX > 24f/);
  assert.match(mainActivity, /dragX < -24f/);
});
